feat: integrate STAC-Catalog feature
aws-solutions-library-samples/guidance-for-processing-overhead-imagery-on-aws pull request #161
Opened 2024-06-03 14:01 UTC by RanbirAulakh

**Issue #, if available:** n/a

### Notes
- Integrate STAC-Catalog feature

### Testing
- The checks may fail, it depends on this [PR](https://github.com/aws-solutions-library-samples/osml-cdk-constructs/pull/114) to be merged in

Before you submit a pull request, please make sure you have to following:

- [x] Your code contains tests that cover all new code and changes
- [x] All new and existing tests passed
- [x] I have read the [Contributing Guidelines](https://github.com/aws-solutions-library-samples/guidance-for-overhead-imagery-inference-on-aws/blob/main/CONTRIBUTING.md) and agree to follow the [Code of Conduct](
https://github.com/aws-solutions-library-samples/guidance-for-overhead-imagery-inference-on-aws/blob/main/CODE_OF_CONDUCT.md))

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-06-03 17:09 UTC, drduhe requested changes

2024-06-03 17:09 UTC, drduhe commented on lib/osml-stacks/stac-catalog/Dockerfile
> +COPY .. /app
Remove this line

2024-06-07 18:48 UTC, drduhe requested changes

2024-06-07 18:48 UTC, drduhe commented on bin/deploy-data-catalog.ts
> +}
Blank line needed

2024-06-07 18:50 UTC, RanbirAulakh commented on bin/deploy-data-catalog.ts
> +}
fixed in latest revision.

2024-06-07 18:56 UTC, drduhe approved these changes
LGTM

2024-06-07 20:59 UTC, merged